### ISSUE TITLE
protonmail 1.8.10 segfaults

### ISSUE THREAD

**Issue by uzytkownik** [ProtonMail/proton-bridge#235]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior
The program crashes after update to 1.8.10

## Current Behavior
```unexpected fault address 0x7f1d17a9d47d
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f1d17a9d47d pc=0x474065]

goroutine 130 [running]:
runtime.throw(0xe220e4, 0x5)
	runtime/panic.go:1117 +0x72 fp=0xc00053b8f8 sp=0xc00053b8c8 pc=0x43b632
runtime.sigpanic()
	runtime/signal_unix.go:741 +0x268 fp=0xc00053b930 sp=0xc00053b8f8 pc=0x452e88
runtime.memmove(0xc009b3c000, 0x7f1d17a9c354, 0x11a9)
	runtime/memmove_amd64.s:332 +0x3c5 fp=0xc00053b938 sp=0xc00053b930 pc=0x474065
bytes.(*Buffer).Read(0xc0078482d0, 0xc009b3c000, 0x11a9, 0x11a9, 0xcd4200, 0xd4e301, 0xc009b3c000)
	bytes/buffer.go:306 +0x10b fp=0xc00053b968 sp=0xc00053b938 pc=0x51a40b
io.(*LimitedReader).Read(0xc00059dd70, 0xc009b3c000, 0x11a9, 0x11a9, 0x0, 0xd9de00, 0xc000700000)
	io/io.go:473 +0x63 fp=0xc00053b9b0 sp=0xc00053b968 pc=0x4a8543
io.copyBuffer(0xf34840, 0xc000760140, 0xf34e00, 0xc00059dd70, 0xc009b3c000, 0x11a9, 0x11a9, 0xddf520, 0x0, 0xf33bc0)
	io/io.go:423 +0x12c fp=0xc00053ba30 sp=0xc00053b9b0 pc=0x4a820c
io.Copy(...)
	io/io.go:382
io.CopyN(0xf34840, 0xc000760140, 0xf33bc0, 0xc0078482d0, 0x11a9, 0x0, 0x0, 0xf3b9f8)
	io/io.go:358 +0x9a fp=0xc00053ba90 sp=0xc00053ba30 pc=0x4a7f3a
github.com/emersion/go-imap.(*Writer).writeLiteral(0xc000760140, 0xf3b9f8, 0xc0078482d0, 0xf3b9f8, 0xc0078482d0)
	github.com/emersion/go-imap@v1.0.6/write.go:166 +0x205 fp=0xc00053bb30 sp=0xc00053ba90 pc=0x981ca5
github.com/emersion/go-imap.(*Writer).writeField(0xc000760140, 0xddf520, 0xc0078482d0, 0x1, 0x1)
	github.com/emersion/go-imap@v1.0.6/write.go:196 +0x5ed fp=0xc00053bb98 sp=0xc00053bb30 pc=0x98272d
github.com/emersion/go-imap.(*Writer).writeFields(0xc000760140, 0xc008d3f600, 0xa, 0x10, 0x1, 0x0)
	github.com/emersion/go-imap@v1.0.6/write.go:104 +0x73 fp=0xc00053bc00 sp=0xc00053bb98 pc=0x981793
github.com/emersion/go-imap.(*Writer).writeList(0xc000760140, 0xc008d3f600, 0xa, 0x10, 0x0, 0xf1fa00)
	github.com/emersion/go-imap@v1.0.6/write.go:117 +0x92 fp=0xc00053bc48 sp=0xc00053bc00 pc=0x981912
github.com/emersion/go-imap.(*Writer).writeField(0xc000760140, 0xcc3620, 0xc00059dd58, 0x1, 0x1)
	github.com/emersion/go-imap@v1.0.6/write.go:198 +0x265 fp=0xc00053bcb0 sp=0xc00053bc48 pc=0x9823a5
github.com/emersion/go-imap.(*Writer).writeFields(0xc000760140, 0xc00cf76400, 0x4, 0x4, 0xc00cf76400, 0x3)
	github.com/emersion/go-imap@v1.0.6/write.go:104 +0x73 fp=0xc00053bd18 sp=0xc00053bcb0 pc=0x981793
github.com/emersion/go-imap.(*Writer).writeLine(0xc000760140, 0xc00cf76400, 0x4, 0x4, 0x3, 0x3)
	github.com/emersion/go-imap@v1.0.6/write.go:235 +0x4d fp=0xc00053bd58 sp=0xc00053bd18 pc=0x982bad
github.com/emersion/go-imap.(*DataResp).WriteTo(0xc00053be48, 0xc000760140, 0x10, 0xc00059dd58)
	github.com/emersion/go-imap@v1.0.6/response.go:127 +0x115 fp=0xc00053bde0 sp=0xc00053bd58 pc=0x978c75
github.com/emersion/go-imap/responses.(*Fetch).WriteTo(0xc000497710, 0xc000760140, 0xc00c764960, 0xc0005a6088)
	github.com/emersion/go-imap@v1.0.6/responses/fetch.go:43 +0x1f6 fp=0xc00053be80 sp=0xc00053bde0 pc=0x98f6b6
github.com/emersion/go-imap/server.(*response).WriteTo(0xc00b9f3038, 0xc000760140, 0x0, 0xf33b80)
	github.com/emersion/go-imap@v1.0.6/server/conn.go:130 +0x3d fp=0xc00053bec0 sp=0xc00053be80 pc=0x995ffd
github.com/emersion/go-imap/server.(*conn).writeAndFlush(0xc00006a960, 0xf349a0, 0xc00b9f3038, 0x0, 0x4)
	github.com/emersion/go-imap@v1.0.6/server/conn.go:190 +0x46 fp=0xc00053bf00 sp=0xc00053bec0 pc=0x9968a6
github.com/emersion/go-imap/server.(*conn).send(0xc00006a960)
	github.com/emersion/go-imap@v1.0.6/server/conn.go:214 +0x272 fp=0xc00053bfd8 sp=0xc00053bf00 pc=0x996bd2
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc00053bfe0 sp=0xc00053bfd8 pc=0x472ec1
created by github.com/emersion/go-imap/server.newConn
	github.com/emersion/go-imap@v1.0.6/server/conn.go:111 +0x27f

(...)
```

## Steps to Reproduce
1. Start the protonmail
2. Connect via IMAP (Evolution)
3. Watch the data being downloaded

## Version Information
1.8.10

## Context (Environment)
I cannot use the program as it crashes early after start

**Comment by andrzejsza** [comment]
closing - if still happens, please contact bridge@protonmail.ch
