### ISSUE TITLE
Protonmail bridge v2.0.1 crashes if Thunderbird tries to fetch mails

### ISSUE THREAD

**Issue by weiznich** [ProtonMail/proton-bridge#248]
## Expected Behavior

Protonmail bridge keeps running and delivering mails to Thunderbird

## Current Behavior

The bridge crashes and does not deliver mails to Thunderbird

## Steps to Reproduce

1. Start the bridge
2. Start Thunderbird
3. Try to fetch mails for one of my accounts

## Version Information

Protonmail bridge v2.0.1
Thunderbird: 91.3.1
Ubuntu: 21.10 (x86_64)

## Context (Environment)

As another detail I should probably add that I run the bridge with "Split addresses" enabled for my account.

## Detailed Description

Starting the bridge from the command line raises the following runtime panic on crash: 

```
panic: runtime error: slice bounds out of range [12:0]

goroutine 121 [running]:
github.com/ProtonMail/proton-bridge/internal/store/cache.(*onDiskCache).Get(0xc0003fe780, 0xc000562000, 0x58, 0xc00060d5c0, 0x58, 0xa84301, 0xc0006062a0, 0x0, 0x0, 0x0)
	github.com/ProtonMail/proton-bridge/internal/store/cache/disk.go:148 +0x392
github.com/ProtonMail/proton-bridge/internal/store.(*Store).getCachedMessage(0xc0001a62d0, 0xc00060d5c0, 0x58, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/ProtonMail/proton-bridge/internal/store/cache.go:114 +0x39c
github.com/ProtonMail/proton-bridge/internal/store.(*Message).GetRFC822Size(0xc0001261c0, 0xc000000070, 0x0, 0x0)
	github.com/ProtonMail/proton-bridge/internal/store/message.go:200 +0x108
github.com/ProtonMail/proton-bridge/internal/imap.(*imapMailbox).getMessage(0xc00050f380, 0x1551e40, 0xc0001261c0, 0xc00061f4c0, 0x4, 0x4, 0x0, 0x0, 0x0)
	github.com/ProtonMail/proton-bridge/internal/imap/mailbox_fetch.go:64 +0x805
github.com/ProtonMail/proton-bridge/internal/imap.(*imapMailbox).listMessages.func2(0x11a8120, 0xc000246d30, 0x1, 0x0, 0x0, 0x0)
	github.com/ProtonMail/proton-bridge/internal/imap/mailbox_messages.go:571 +0x365
github.com/ProtonMail/proton-bridge/pkg/parallel.RunParallel.func2(0xc000931ae0, 0xc000949320, 0xc00061f600, 0xc000246d90, 0xc000949380)
	github.com/ProtonMail/proton-bridge/pkg/parallel/parallel.go:79 +0xce
created by github.com/ProtonMail/proton-bridge/pkg/parallel.RunParallel
	github.com/ProtonMail/proton-bridge/pkg/parallel/parallel.go:76 +0x1db
time="Jan  7 09:28:14.760" level=fatal msg="Failed to launch" error="exit status 2"
```
I suspect that this panic causes the crash.

I'm happy to provide more details if required. Feel free to reach out for that.

**Comment by andrzejsza** [comment]
thanks for the report. it's a knows issue and will be fixed in the upcoming release - will update here once it's out in beta.

**Comment by andrzejsza** [comment]
and it should be all fine now as per 2.1.0 - can you confirm?

**Comment by weiznich** [comment]
Thanks for the update. I can confirm that the issue is fixed.
