### ISSUE TITLE
Crash on startup on Archlinux with WSL

### ISSUE THREAD

**Issue by daedsidog** [ProtonMail/proton-bridge#496]
Installing from pacman causing this on startup:

```
[daedsidog@DESKTOP-OC5833J ~]$ protonmail-bridge
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Failed to initialize sentry
INFO[Oct 08 04:01:10.901] bridge-gui starting
INFO[Oct 08 04:01:10.901] Using Qt 6.7.3 (compiled against 6.7.2)
INFO[Oct 08 04:01:10.907] lock file created /home/daedsidog/.cache/protonmail/bridge-v3/bridge-v3-gui.lock
INFO[Oct 08 04:01:10.907] bridge-gui executable: protonmail-bridge
INFO[Oct 08 04:01:10.907] Command-line invocation: <none>
INFO[Oct 08 04:01:10.907] New Sentry reporter - id: xQf5V7ofFifwQ/6o83X6EBGXTIvO5EYrhJjgmnaMXVk=.
DEBU[Oct 08 04:01:10.910] Bridge executable path: /usr/lib/protonmail/bridge/bridge
INFO[Oct 08 04:01:10.910] Launching bridge process with command "/usr/lib/protonmail/bridge/bridge" --grpc --parent-pid 9474 --launcher protonmail-bridge --session-id 20241008_040110901
INFO[Oct 08 04:01:10.910] Retrieving gRPC service configuration from '/home/daedsidog/.config/protonmail/bridge-v3/grpcServerConfig.json'
ERRO[Oct  8 04:01:10.925] Failed to execute recovery action             error="exit status 1"
WARN[Oct  8 04:01:10.925] Captured exception                            error="recover: runtime error: slice bounds out of range [162:136]" reportID=7382eb0e15f34bac9012526cedf7c6f8
ERRO[Oct  8 04:01:10.929] Failed to execute recovery action             error="exit status 1"
WARN[Oct  8 04:01:10.929] Saved crash report                            file=/home/daedsidog/.local/share/protonmail/bridge-v3/logs/20241008_040110901_bridge_000_v3.13.0_v3.13.0_crash.log
reportID: 00000000000000000000000000000000 Captured exception :waitAndRetrieveServiceConfig(): Bridge failed to start.

Details:
Bridge application exited before providing a gRPC service configuration file
```

## Version Information
```
[daedsidog@DESKTOP-OC5833J ~]$ pacman -Qi protonmail-bridge
Name            : protonmail-bridge
Version         : 3.13.0-2
Description     : Integrate ProtonMail paid account with any program that supports IMAP and SMTP (Qt desktop application)
Architecture    : x86_64
URL             : https://github.com/ProtonMail/proton-bridge
Licenses        : GPL-3.0-only
Groups          : None
Provides        : None
Depends On      : protonmail-bridge-core  abseil-cpp  gcc-libs  glibc  grpc  hicolor-icon-theme  protobuf  qt6-base  qt6-declarative
                  qt6-svg  sentry-native
Optional Deps   : qt6-wayland: Wayland support
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 3.13 MiB
Packager        : Christian Heusel <gromit@archlinux.org>
Build Date      : Mon 23 Sep 2024 10:41:27 PM IDT
Install Date    : Tue 08 Oct 2024 03:56:18 AM IDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

## Context (Environment)

Archlinux on WSL2, systemd disabled

Associated crash log:

```
Recover: runtime error: slice bounds out of range [162:136]goroutine 1 [running]:
runtime/pprof.writeGoroutineStacks({0x55b5cb431420, 0xc0001a2e68})
	/usr/lib/go/src/runtime/pprof/pprof.go:761 +0x6a
runtime/pprof.writeGoroutine({0x55b5cb431420?, 0xc0001a2e68?}, 0xd0?)
	/usr/lib/go/src/runtime/pprof/pprof.go:750 +0x25
runtime/pprof.(*Profile).WriteTo(0x55b5caf7f878?, {0x55b5cb431420?, 0xc0001a2e68?}, 0x1?)
	/usr/lib/go/src/runtime/pprof/pprof.go:374 +0x14b
github.com/ProtonMail/proton-bridge/v3/internal/app.withLogging.DumpStackTrace.func1({0x55b5cb39c280, 0xc0001e5998})
	/build/protonmail-bridge/src/proton-bridge/internal/logging/crash.go:45 +0x166
github.com/ProtonMail/proton-bridge/v3/internal/crash.(*Handler).HandlePanic(0xc0001a1518, {0x55b5cb39c280, 0xc0001e5998})
	/build/protonmail-bridge/src/proton-bridge/internal/crash/handler.go:49 +0x82
github.com/ProtonMail/gluon/async.HandlePanic({0x55b5cb431660, 0xc0001a1518})
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/ProtonMail/gluon/async/panic_handler.go:24 +0x74
panic({0x55b5cb39c280?, 0xc0001e5998?})
	/usr/lib/go/src/runtime/panic.go:785 +0x132
github.com/godbus/dbus.getSessionBusPlatformAddress()
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/godbus/dbus/conn_other.go:30 +0x1d1
github.com/godbus/dbus.getSessionBusAddress()
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/godbus/dbus/conn.go:96 +0xf1
github.com/godbus/dbus.SessionBusPrivate()
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/godbus/dbus/conn.go:101 +0x13
github.com/godbus/dbus.SessionBus()
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/godbus/dbus/conn.go:73 +0xbc
github.com/keybase/go-keychain/secretservice.NewService()
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/keybase/go-keychain/secretservice/secretservice.go:73 +0x17
github.com/ProtonMail/proton-bridge/v3/pkg/keychain.getSession()
	/build/protonmail-bridge/src/proton-bridge/pkg/keychain/helper_dbus_linux.go:43 +0x13
github.com/ProtonMail/proton-bridge/v3/pkg/keychain.(*SecretServiceDBusHelper).Add(0x0?, 0xc000435020)
	/build/protonmail-bridge/src/proton-bridge/pkg/keychain/helper_dbus_linux.go:98 +0x45
github.com/ProtonMail/proton-bridge/v3/pkg/keychain.isUsable.func1()
	/build/protonmail-bridge/src/proton-bridge/pkg/keychain/keychain.go:224 +0x22
github.com/ProtonMail/proton-bridge/v3/pkg/keychain.retry(0xc000331e28)
	/build/protonmail-bridge/src/proton-bridge/pkg/keychain/keychain.go:263 +0x3f
github.com/ProtonMail/proton-bridge/v3/pkg/keychain.isUsable({0x55b5cb440c08, 0x55b5cbd93400}, {0x0, 0x0})
	/build/protonmail-bridge/src/proton-bridge/pkg/keychain/keychain.go:223 +0x28f
github.com/ProtonMail/proton-bridge/v3/pkg/keychain.listHelpers(0x60?)
	/build/protonmail-bridge/src/proton-bridge/pkg/keychain/helper_linux.go:37 +0x3e
github.com/ProtonMail/proton-bridge/v3/pkg/keychain.NewList(...)
	/build/protonmail-bridge/src/proton-bridge/pkg/keychain/keychain.go:67
github.com/ProtonMail/proton-bridge/v3/internal/app.WithKeychainList({0x55b5cb431660, 0xc0001a1518}, 0x0, 0xc000332270)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:529 +0x185
github.com/ProtonMail/proton-bridge/v3/internal/app.run.func2.1.1.1.1.1()
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:261 +0xb0
github.com/ProtonMail/proton-bridge/v3/internal/app.withSingleInstance({0xc0003fe0f0, 0x2c}, {0xc00039d980, 0x3a}, 0xc0003a62d0, 0xc000332460)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:352 +0x23e
github.com/ProtonMail/proton-bridge/v3/internal/app.run.func2.1.1.1.1({0x55b5cb431540?, 0xc00039f280?})
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:258 +0x307
github.com/ProtonMail/proton-bridge/v3/internal/app.withLogging(0xc00039e880, 0xc0001a1518, 0xc0003a65a0, 0xc0003334a8)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:414 +0xfb2
github.com/ProtonMail/proton-bridge/v3/internal/app.run.func2.1.1.1(0xc0003a65a0)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:244 +0x1fe
github.com/ProtonMail/proton-bridge/v3/internal/app.WithLocations(0xc0003335f8)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:429 +0x193
github.com/ProtonMail/proton-bridge/v3/internal/app.run.func2.1.1()
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:237 +0xc8
github.com/ProtonMail/proton-bridge/v3/internal/app.withProfiler(0xc00039e880, 0xc000333828)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:451 +0x3b0
github.com/ProtonMail/proton-bridge/v3/internal/app.run.func2.1(0xc0001a1518, 0xc000182930)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:235 +0x13e
github.com/ProtonMail/proton-bridge/v3/internal/app.withCrashHandler(0xc0003cb380, 0xc00039f1c0, 0xc0003339d0)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:488 +0x555
github.com/ProtonMail/proton-bridge/v3/internal/app.run.func2(0x6?)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:231 +0x8a
github.com/ProtonMail/proton-bridge/v3/internal/app.withRestarter({0x7fffea282b8d, 0x11}, 0xc000333b78)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:462 +0x124
github.com/ProtonMail/proton-bridge/v3/internal/app.run(0xc00039e880)
	/build/protonmail-bridge/src/proton-bridge/internal/app/app.go:229 +0x2bf
github.com/urfave/cli/v2.(*Command).Run(0xc0001c7760, 0xc00039e880, {0xc000380a00, 0x8, 0x8})
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/urfave/cli/v2/command.go:273 +0x7a2
github.com/urfave/cli/v2.(*App).RunContext(0xc0002f25a0, {0x55b5cb440aa8, 0x55b5cbd93400}, {0xc000380a00, 0x8, 0x8})
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/urfave/cli/v2/app.go:332 +0x566
github.com/urfave/cli/v2.(*App).Run(0x0?, {0xc000380a00?, 0x8?, 0x55b5ca41b5a5?})
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/urfave/cli/v2/app.go:309 +0x2f
main.main()
	/build/protonmail-bridge/src/proton-bridge/cmd/Desktop-Bridge/main.go:53 +0x58

goroutine 20 [select]:
io.(*pipe).read(0xc0001cfe00, {0xc0000b6000, 0x1000, 0x1?})
	/usr/lib/go/src/io/pipe.go:57 +0xa5
io.(*PipeReader).Read(0x0?, {0xc0000b6000?, 0x0?, 0x0?})
	/usr/lib/go/src/io/pipe.go:134 +0x1a
bufio.(*Scanner).Scan(0xc000093f28)
	/usr/lib/go/src/bufio/scan.go:219 +0x81e
github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0003af810, 0xc0001cfe00, 0xc0002a1f50)
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/sirupsen/logrus/writer.go:59 +0xa5
created by github.com/sirupsen/logrus.(*Entry).WriterLevel in goroutine 1
	/build/protonmail-bridge/src/proton-bridge/vendor/github.com/sirupsen/logrus/writer.go:51 +0x31f
```

**Comment by Antiz96** [comment]
> qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

You most likely need to install the additional `qt6-wayland`. It is required to run `Qt` applications on Wayland, see https://wiki.archlinux.org/title/Wayland#Qt

**Comment by daedsidog** [comment]
> Don't know if that will solve your issue completely, but you most likely need to install the additional `qt6-wayland` package. It is required to run `Qt` applications on Wayland, see https://wiki.archlinux.org/title/Wayland#Qt

Done. I now don't get the Qt message, but the error looks similar still.

```
[daedsidog@DESKTOP-OC5833J ~]$ protonmail-bridge
Failed to initialize sentry
INFO[Dec 04 03:13:49.148] bridge-gui starting
INFO[Dec 04 03:13:49.148] Using Qt 6.8.1 (compiled against 6.8.0)
INFO[Dec 04 03:13:49.151] lock file created /home/daedsidog/.cache/protonmail/bridge-v3/bridge-v3-gui.lock
INFO[Dec 04 03:13:49.151] bridge-gui executable: protonmail-bridge
INFO[Dec 04 03:13:49.151] Command-line invocation: <none>
INFO[Dec 04 03:13:49.151] New Sentry reporter - id: xQf5V7ofFifwQ/6o83X6EBGXTIvO5EYrhJjgmnaMXVk=.
DEBU[Dec 04 03:13:49.155] Bridge executable path: /usr/lib/protonmail/bridge/bridge
INFO[Dec 04 03:13:49.155] Launching bridge process with command "/usr/lib/protonmail/bridge/bridge" --grpc --parent-pid 2069 --launcher protonmail-bridge --session-id 20241204_031349148
INFO[Dec 04 03:13:49.155] Retrieving gRPC service configuration from '/home/daedsidog/.config/protonmail/bridge-v3/grpcServerConfig.json'
ERRO[Dec  4 03:13:49.174] Failed to execute recovery action             error="exit status 1"
WARN[Dec  4 03:13:49.175] Captured exception                            error="recover: runtime error: slice bounds out of range [162:136]" reportID=fb0b7785e27044469ff161f5f09c779e
ERRO[Dec  4 03:13:49.178] Failed to execute recovery action             error="exit status 1"
WARN[Dec  4 03:13:49.179] Saved crash report                            file=/home/daedsidog/.local/share/protonmail/bridge-v3/logs/20241204_031349148_bridge_000_v3.15.0_v3.15.0_crash.log
reportID: 00000000000000000000000000000000 Captured exception :waitAndRetrieveServiceConfig(): Bridge failed to start.

Details:
Bridge application exited before providing a gRPC service configuration file
[daedsidog@DESKTOP-OC5833J ~]$ 
```
