### ISSUE TITLE
vault-editor is unstable becacause it tries to add and remove test credentials to the keychain (and there is an unnecessary dbus dependency?)

### ISSUE THREAD

**Issue by simonfelding** [ProtonMail/proton-bridge#512]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

I'm trying to run protonmail-bridge in a container, and I want to use vault-editor to modify the settings in the vault.enc file.

I'm doing the following before starting protonmail-bridge to make sure things are as expected:
```
    /protonmail/vault-editor read | \
    jq '.Settings.AutoUpdate = env.PROTONMAIL_AutoUpdate 
    | .Settings.TelemetryDisabled = env.PROTONMAIL_TelemetryDisabled
    | .Settings.GluonDir |= "\(env.HOME)/.local/share/protonmail/bridge-v3/gluon"
    | .Settings.Autostart = false
    | .Settings.SMTPPort = 1025
    | .Settings.IMAPPort = 1143 ' \
    | /protonmail/vault-editor write
```

## Expected Behavior
I expect that `vault-editor read` outputs json to stdout, and `vault-editor write` takes json from stdin and saves it to the vault.enc file.

## Current Behavior
I get this error when `vault-editor read` is run: 

`level=warning msg="Failed to add test credentials to keychain" error="failed to open dbus connection: exec: \"dbus-launch\": executable file not found in $PATH" helper="*keychain.SecretServiceDBusHelper"`

I do not have dbus installed in my docker image, and why should I? I don't need to add test credentials?
It does output the json data just fine though.

When the result is piped to `vault-editor write`, I get the following messages:

`level=warning msg="Failed to delete test credentials from keychain" error="exit status 1: Error: docker-credential-helpers/YnJpZGdlL2NoZWNr is not in the password store.\n" helper="*pass.Pass"`

`level=error msg="Could not load/create vault key" error="could not create keychain: no keychain"`

```
panic: json: cannot unmarshal string into Go struct field Settings.Settings.AutoUpdate of type bool

goroutine 1 [running]:
main.writeAction.func1.1.1.(*Vault).ImportJSON.1(0xe330d0?)
        /build/proton-bridge/internal/vault/vault_debug.go:29 +0x54
github.com/ProtonMail/proton-bridge/v3/internal/vault.(*Vault).modUnsafe(0x4000340690, 0x40002a3528)
        /build/proton-bridge/internal/vault/vault.go:418 +0x8c
github.com/ProtonMail/proton-bridge/v3/internal/vault.(*Vault).modSafe(0x4000340690, 0x40002a3528)
        /build/proton-bridge/internal/vault/vault.go:408 +0x70
github.com/ProtonMail/proton-bridge/v3/internal/vault.(*Vault).ImportJSON(...)
        /build/proton-bridge/internal/vault/vault_debug.go:27
main.writeAction.func1.1.1(0x4000340690, 0xb7?, 0xc2?)
        /build/proton-bridge/utils/vault-editor/main.go:75 +0x9c
github.com/ProtonMail/proton-bridge/v3/internal/app.WithVault(0x0, 0x4000318280, 0x4000356180, {0xe36060, 0x14b9260}, 0xd6b400)
        /build/proton-bridge/internal/app/vault.go:58 +0x348
main.writeAction.func1.1(0x4000332960?)
        /build/proton-bridge/utils/vault-editor/main.go:69 +0x40
github.com/ProtonMail/proton-bridge/v3/internal/app.WithKeychainList({0xe36060, 0x14b9260}, 0x0, 0x40002a38a8)
        /build/proton-bridge/internal/app/app.go:554 +0x19c
main.writeAction.func1(0xe3d7f8?)
        /build/proton-bridge/utils/vault-editor/main.go:68 +0x44
github.com/ProtonMail/proton-bridge/v3/internal/app.WithLocations(0xd6b3f8)
        /build/proton-bridge/internal/app/app.go:454 +0x164
main.writeAction(0x400030c940?)
        /build/proton-bridge/utils/vault-editor/main.go:67 +0x24
github.com/urfave/cli/v2.(*Command).Run(0x40001c94a0, 0x400030c940, {0x4000334720, 0x1, 0x1})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/command.go:273 +0x5e0
github.com/urfave/cli/v2.(*Command).Run(0x40001c9760, 0x400030c880, {0x400013e000, 0x2, 0x2})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/command.go:266 +0x81c
github.com/urfave/cli/v2.(*App).RunContext(0x400026a5a0, {0xe3e8e8, 0x14b9260}, {0x400013e000, 0x2, 0x2})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:332 +0x4f8
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:309
github.com/urfave/cli/v2.(*App).RunAndExitOnError(0x400026a5a0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:373 +0x48
main.main()
```

## Possible Solution
Stop trying to add the docker credential helper and remove the dbus dependency if it isn't needed

## Steps to Reproduce

1. With protonmail set up using gpg and Pass, run the following command:

```
    /protonmail/vault-editor read | \
    jq '.Settings.AutoUpdate = env.PROTONMAIL_AutoUpdate 
    | .Settings.TelemetryDisabled = env.PROTONMAIL_TelemetryDisabled
    | .Settings.GluonDir |= "\(env.HOME)/.local/share/protonmail/bridge-v3/gluon"
    | .Settings.Autostart = false
    | .Settings.SMTPPort = 1025
    | .Settings.IMAPPort = 1143 ' \
    | /protonmail/vault-editor write
```

Note: It can be reproduced using[ this container](https://github.com/simonfelding/protonmail-bridge-docker/pkgs/container/protonmail/320874154?tag=3.15.0-rootless) (with already prepared data mounted in /root). see `/protonmail/entrypoint.sh`.

## Version Information
3.15.1+git

## Context (Environment)
I'm trying to run the protonmail-bridge in Kubernetes.

**Comment by simonfelding** [comment]
Okay turns out it actually does work, it just prints an error even though it doesn't fail.
